home: "{{ ansible_env.HOME }}"

xdg_bin: "{{ home }}/.local/bin"
xdg_config_home: "{{ home }}/.config"
xdg_data_home: "{{ home }}/.local/share"
xdg_cache_home: "{{ home }}/.cache"

st_default_terminal_emulator: true

pyenv_global_python: "3.11.1"

repositories:
  - repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    key: https://apt.releases.hashicorp.com/gpg
    fingerprint: "E8A0 32E0 94D8 EB4E A189 D270 DA41 8C88 A321 9F7B"
    filename: hashicorp

  - repo: "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    key: https://packages.microsoft.com/keys/microsoft.asc
    fingerprint: "BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF"
    filename: microsoft

  - repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    key: https://download.docker.com/linux/ubuntu/gpg
    fingerprint: 9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88
    filename: docker

packages:
  - code
  - neovim

  - xclip
  - curl
  - wget
  - make
  - jq
  - htop
  - bpftrace
  - gnupg
  - ripgrep
  - fzf

  - vagrant
  - packer

  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

vscode_extensions:
  - ms-dotnettools.csharp
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-azuretools.vscode-docker
  - eamodio.gitlens
  - zhuangtongfa.material-theme
  - jtlowe.vscode-icon-theme
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  - streetsidesoftware.code-spell-checker
  - github.vscode-pull-request-github
  - editorconfig.editorconfig
  - pflannery.vscode-versionlens
  - golang.go
  - rust-lang.rust-analyzer
  - hashicorp.terraform
  - denoland.vscode-deno
  - redhat.ansible
