home: "{{ ansible_env.HOME }}"

xdg_bin: "{{ home }}/.local/bin"
xdg_config_home: "{{ home }}/.config"
xdg_data_home: "{{ home }}/.local/share"
xdg_cache_home: "{{ home }}/.cache"

st_patch_libxft: true
st_default_terminal_emulator: true

keys:
  - https://apt.releases.hashicorp.com/gpg
  - https://packages.microsoft.com/keys/microsoft.asc # https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions
  - https://dl.yarnpkg.com/debian/pubkey.gpg

repositories:
  - repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp

  - repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode

  - repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn

packages:
  - code
  - neovim

  - xclip
  - curl
  - wget
  - make
  - jq
  - htop
  - bpftrace
  - gnupg

  - vagrant
  - packer

vscode_extensions:
  - ms-dotnettools.csharp
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-azuretools.vscode-docker
  - eamodio.gitlens
  - zhuangtongfa.material-theme
  - jtlowe.vscode-icon-theme
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  - streetsidesoftware.code-spell-checker
  - github.vscode-pull-request-github
  - editorconfig.editorconfig
  - pflannery.vscode-versionlens
  - golang.go
  - rust-lang.rust-analyzer
  - hashicorp.terraform
  - denoland.vscode-deno
  - redhat.ansible
