- name: Linux Dev Machine Setup Playbook
  hosts: all
  gather_facts: yes

  vars_files:
    - default.config.yml

  roles:
    - role: vandycknick.dotfiles
    - role: vandycknick.python
    - role: vandycknick.terminal.st
    - role: vandycknick.terminal.zsh
    - role: vandycknick.terminal.tmux

  tasks:
    - import_tasks: tasks/packages.yml
      tags:
        - packages

    - name: Install vscode extensions
      vscode_extension:
        name: "{{ item }}"
        extensions_dir: "{{ xdg_data_home }}/vscode/extensions"
        state: present
      with_items: "{{ vscode_extensions }}"
      tags:
        - vscode
