- name: Apt Update registry
  apt:
    update_cache: yes
  become: true

- name: Install keyring
  shell: |
    curl -fsSL {{ item.key }} | gpg --dearmor -o /usr/share/keyrings/{{ item.filename }}.gpg
    gpg --no-default-keyring  --keyring /usr/share/keyrings/{{ item.filename }}.gpg --list-keys "{{ item.fingerprint }}" 2> /dev/null
    valid_key=$?

    if [ "$valid_key" -gt 0 ]; then
      >&2 echo "GPG Key not matching fingerprint!"
      rm /usr/share/keyrings/{{ item.filename }}.gpg
    fi

    exit "$valid_key"
  args:
    creates: /usr/share/keyrings/{{ item.filename }}.gpg
  become: true
  with_items: "{{ repositories }}"

- name: Add extra repositories
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename }}"
    state: present
  become: true
  with_items: "{{ repositories }}"

- name: Apt Update registry
  apt:
    update_cache: yes
  become: true

- name: Install packages
  apt:
    name: "{{ item }}"
  become: true
  with_items: "{{ packages }}"
